- id: '1684703376299'
  alias: Power on LG TV
  description: Power on the main living room TV
  trigger:
  - platform: device
    device_id: 9da212e6abf5c6272b4d5c9359565f3c
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 20:17:42:72:DD:D9
  mode: single
- id: '1684955651080'
  alias: '[Notify] - Water leak'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matan_s23
    data:
      message: Water leak at {{ trigger.name }}
      title: Wate leak
  - service: notify.mobile_app_hen_s23
    data:
      message: Water leak at {{ trigger.name }}
      title: Water leak
  mode: single
- id: '1685172148575'
  alias: '[Notify] - Storage door open'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.storage_door_contact
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_matan_s23
    data:
      message: Storage door is open
  - service: notify.mobile_app_hen_s23
    data:
      message: Storage door is open
    enabled: true
  mode: single
- id: '1685305554885'
  alias: '[Startup] - Apply default theme'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      mode: dark
      name: noctis
  mode: single
- id: '1690898247747'
  alias: '[Motion] - Parents bathroom LED On\Off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.parents_bathroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: parents_bathroom_motion_detected
  - type: occupied
    platform: device
    device_id: 8980b06e19a58d5623a2f86d18baa332
    entity_id: cf40d72b78eb93ac41a1e5dc72083999
    domain: binary_sensor
    id: parents_bathroom_occupancy_detected
  - type: not_occupied
    platform: device
    device_id: 8980b06e19a58d5623a2f86d18baa332
    entity_id: cf40d72b78eb93ac41a1e5dc72083999
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 5
    id: parents_bathroom_no_occupancy
  condition:
  - condition: sun
    before: sunrise
    after: sunset
    enabled: true
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - parents_bathroom_motion_detected
        - parents_bathroom_occupancy_detected
      sequence:
      - type: turn_on
        device_id: 8d295f7e94d98f23db6c37d11166633d
        entity_id: ad4c403daa105bc6586da91267e7528d
        domain: light
        brightness_pct: 1
    - conditions:
      - condition: trigger
        id:
        - parents_bathroom_no_occupancy
      sequence:
      - type: turn_off
        device_id: 8d295f7e94d98f23db6c37d11166633d
        entity_id: ad4c403daa105bc6586da91267e7528d
        domain: light
  mode: single
- id: '1694193356542'
  alias: '[Motion] - MaIn bathroom light On\Off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.main_bathroom_presence_ld1125h_occupancy_or_movement
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: occupancy_detected
  - type: motion
    platform: device
    device_id: f833657afd2a39c49f299d2b02418fb2
    entity_id: 472ebd8011923fe95e3d2e575a7a4bb3
    domain: binary_sensor
    id: motion_detected
  - type: not_occupied
    platform: device
    device_id: 88a7e45d9e4a6283bb6f5724fe4eb4b5
    entity_id: b1400796cdcc5f2758d9ebaf2ead2ad1
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 15
    id: no_occupancy
  - type: no_motion
    platform: device
    device_id: f833657afd2a39c49f299d2b02418fb2
    entity_id: 472ebd8011923fe95e3d2e575a7a4bb3
    domain: binary_sensor
    id: no_motion
    for:
      hours: 0
      minutes: 0
      seconds: 15
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id:
          - occupancy_detected
        - condition: trigger
          id:
          - motion_detected
      sequence:
      - type: turn_on
        device_id: 9700798447239bb9c80eb4fd137b5d23
        entity_id: 6612f42484e0670192954f8b2747205f
        domain: light
  mode: single
- id: '1696092829450'
  alias: '[Sun] - TV counter led On\Off'
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
    id: sunset
  - platform: sun
    event: sunrise
    offset: 0
    id: sunrise
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.wled_tv_counter
  - choose:
    - conditions:
      - condition: trigger
        id:
        - sunset
      sequence:
      - type: turn_on
        device_id: 17ad5a48f112c9a6189d729db701b302
        entity_id: 41bb32b2b759a8e7450a7714eb7b379b
        domain: light
    - conditions:
      - condition: trigger
        id:
        - sunrise
      sequence:
      - type: turn_off
        device_id: 17ad5a48f112c9a6189d729db701b302
        entity_id: 41bb32b2b759a8e7450a7714eb7b379b
        domain: light
  mode: single
- id: '1697396097180'
  alias: '[Time] - Living room TV morning protection'
  description: ''
  trigger:
  - platform: time
    at: '19:30:00'
    id: turn_on_time
  - platform: time
    at: 06:30:00
    id: turn_off_time
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - turn_on_time
      sequence:
      - type: turn_on
        device_id: 42b83ade3def14a661eec3d107164ba9
        entity_id: 7cd0d46b3df7f185433c1eab0b7e02d5
        domain: switch
    - conditions:
      - condition: trigger
        id:
        - turn_off_time
      sequence:
      - type: turn_off
        device_id: 42b83ade3def14a661eec3d107164ba9
        entity_id: 7cd0d46b3df7f185433c1eab0b7e02d5
        domain: switch
  mode: single
- id: '1703401860070'
  alias: TEST MOTION
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.main_bathroom_presence_ld1125h_occupancy_or_movement
    from:
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: occupancy_detected
  - type: motion
    platform: device
    device_id: f833657afd2a39c49f299d2b02418fb2
    entity_id: 472ebd8011923fe95e3d2e575a7a4bb3
    domain: binary_sensor
    id: motion_detected
  - type: not_occupied
    platform: device
    device_id: 88a7e45d9e4a6283bb6f5724fe4eb4b5
    entity_id: b1400796cdcc5f2758d9ebaf2ead2ad1
    domain: binary_sensor
    id: no_occupancy
  - type: no_motion
    platform: device
    device_id: f833657afd2a39c49f299d2b02418fb2
    entity_id: 472ebd8011923fe95e3d2e575a7a4bb3
    domain: binary_sensor
    id: no_motion
    for:
      hours: 0
      minutes: 0
      seconds: 15
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: trigger
          id:
          - occupancy_detected
        - condition: trigger
          id:
          - motion_detected
      sequence:
      - type: turn_on
        device_id: 9700798447239bb9c80eb4fd137b5d23
        entity_id: 6612f42484e0670192954f8b2747205f
        domain: light
    - conditions:
      - condition: and
        conditions:
        - condition: trigger
          id:
          - no_occupancy
      sequence:
      - type: turn_off
        device_id: 9700798447239bb9c80eb4fd137b5d23
        entity_id: 6612f42484e0670192954f8b2747205f
        domain: light
      - type: turn_off
        device_id: 9700798447239bb9c80eb4fd137b5d23
        entity_id: cb8d8115623fe7b13182a8381f1d9bf0
        domain: light
      - type: turn_off
        device_id: 9700798447239bb9c80eb4fd137b5d23
        entity_id: 96c0a6f417ed9f03bcf3d2756a12f5bc
        domain: switch
  mode: single
